# Configuración específica para desarrollo
spring.profiles.active=dev

# Configuración específica de desarrollo
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.com.example.tureserva=DEBUG

# Hot reload para desarrollo
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true